const ingredientsList = [
    { id: 1, name: 'Olive oil' },
    { id: 2, name: 'All purpose flour' },
    { id: 3, name: 'Butter' },
    { id: 4, name: 'Chicken' },
    { id: 5, name: 'Sugar' },
    { id: 6, name: 'Salt' },
    { id: 7, name: 'Egg' },
    { id: 8, name: 'Rice' },
    { id: 9, name: 'Vegetable oil' },
    { id: 10, name: 'Pork' },
    { id: 11, name: 'Beef' },
    { id: 12, name: 'Cheese' },
    { id: 13, name: 'Garlic' },
    { id: 14, name: 'Orange' },
    { id: 15, name: 'Turkey' },
    { id: 16, name: 'Onion' },
    { id: 17, name: 'Corn' },
    { id: 18, name: 'Whole milk' },
    { id: 19, name: 'Mayonnaise' },
    { id: 20, name: 'Chiles' },
    { id: 21, name: 'Almonds' },
    { id: 22, name: 'Bacon' },
    { id: 23, name: 'Mushrooms' },
    { id: 24, name: 'Coconut' },
    { id: 25, name: 'Beets' },
    { id: 26, name: 'Strawberries' },
    { id: 27, name: 'Fennel' },
    { id: 28, name: 'Lamb' },
    { id: 29, name: 'Apple' },
    { id: 30, name: 'Shrimp' },
    { id: 31, name: 'Beans' },
    { id: 32, name: 'Tomato' },
    { id: 33, name: 'Cucumber' },
    { id: 34, name: 'Pickles' },
    { id: 35, name: 'Iceberg salad' },
];

export default ingredientsList;
